// Package Swagger provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/pseudo-su/oapi-ui-codegen DO NOT EDIT.
package Swagger

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x863Lbtrbwq6zh983E7qEpkuJNnskPN83Jzmkap3H26cyuMh6IhCTskAALgHY0Gb/7",
	"mQVeREmUbKXObtom/VGKANf9Cqzkk5WKohSccq2s80+WSpe0IObxGdF0ISSj5hfTtDAP/1/SuXVu/b/R",
	"+sNR89XonWRlTrV1Z1t6VVLr3CJSkhX+fi6lkPh9KUVJpW7A0vZ1RlUqWamZ4NZ5/RoKqhRZUMu26EdS",
	"lDkCTEWVZ8CFBkVWsKR5LqwOm9KS8YV1d2dbkv5WMUkz6/zXBsn7bpuY/Zumhsp/UJLr5S5Z6ZKmHx7O",
	"dw3mGX5E5RD3ShOprzUr6C6v75YUzDpkRFMgPAPcCGIOF29egqw4R6b6QvBd3z1zozPPe+d558Hk3Pec",
	"0Hcnvv+vXWEY7LpSezHrSiEyvaSIEBHxqkC5Xf5o2dYvF29fv3z9wrKtZ29fvnv57OJVT5JrHFW5n7t6",
	"rWFog5FxEHrREMk3VCoDYFszs4rl2QFJmvVdSfaYG5Sib6To/pfrnbvuEEELpq9TURRMD+NdMA31OiyJ",
	"Wu7DGaf+nM5mc3+WeIkXh57nB3GSBfP5jGQzSr1ZFAbzaDxEQk74okJ/GCSglGIhSVEwvoB2J1SKZqAF",
	"MERfUK53CFqIQ6iue3rYRdkstrx+NgWe4wXO+B4zOIh+G6bnuI47GBe2QsDd3qDQevOOBeZE6WsTIDC6",
	"DBGGO2BpoIDZOGyP9KOmkpMcFJU3LKWHXTx0nfHYdZPJv4YVpvT1nLC8kvQAUbiDZr+fNm9y5k7OfN/Q",
	"lpyHnuOaP95+4lSVplSpA8Q1O+ZV/h8WXptnBklrFrcC5UH0heALkc2AKTAhdAchJ/vCF64gjm34tR/N",
	"VlsRusE0GJEfHvWHmDk6BQx50k9Uk4xoMpBgRWYksFc0u+zk1WJwQZNZTu8vTepdB8l8S1UpuKIPzvsd",
	"fwMp3yAcYHyjqjoEvFd/3dmPKjChSf7gUm5IYO86kT+sLDSiGJJRg+TLmcdAxL+zLcbnYtcx/pvxDF5y",
	"xRZLreAFFahaU4MxBaTzxLmQ8FtF5QrzXEq5qhSGKDIqGmtAN11QzIXlcgUnSHLWvWBUgZBwQyQTlYJU",
	"CJkxTjQ9mxF0cYTMqDp1LNvKGYI3/NZ8W5cl5fBC3FDJTS59hTtSCjdjk+4qmVvn1lLr8nw0ur29dThB",
	"3khOZLpkN1Q5C3HjVB9GmUhHoqT8bNHBOstrWKMmrY7GI6Mypk1My8qzRS2RM1Iyq5eam2R7Z1sIERfP",
	"rXGTf0uil0aho/RDQQlXo08rSuQdvlrQgVLqn4oqaPYCydH+9bLAAoIqzQrMBJzoSpIcZpKSD6VgXCtg",
	"3ASyBbuhvK8TaNxtBSffpUR/ByWRpKCaylMbpnzOck1lXaAInq9AiltlFIzQVElTNmc95a0AjQlOvltQ",
	"gU99eA68pbqSXMH/XF2+hluml5AzpdsgO+UF+ciKqoAbkldUwQlzqGOWqrKkssfPKfJDSbpsJAFpXilN",
	"pQ0f6Kqmdib0EhoqTG7sGJ3yE0UxpptspE4duCxrI8hXkBLeCbJmtDZYRG2kKNFgTGIQnK6BagGEC71E",
	"GljNz5OM3bCMXs9WT6a8EwO6iqrKMkexGUJmNBe3p86UT/lFrgTIRkoECsavC/IRTDgwxNQ8t0hHHYPY",
	"zFGlaQZnoJdM1Q6pb8WZkWUDwYgcSSsYn3IUCkJvpN0qdW0QktwiLx0bpqksRVnlRNPMRigjBNCIhM2B",
	"aWAKWTGW3XCsrPNft634WW2BaOoOPKukpFznKyA3hOUYC8+n/Ax81/MMKIafoKdYbXyz8Eur38RqWVG7",
	"6c57YY5xTRfYct7ZQ2l+0BO0gJTkqWFzQ/1zIR00n9ffwxnWG9AFNMozY5j4Leq0tet0l7U+ThTVM8Jh",
	"hgwDnIFifJHTzgGos3Dg5yvf9Z//4rquf1rvwjaKnCmKIkad19oV8/53vc/G9vBzcIo291OVa0wyyL9a",
	"u6syrjCjnbHaYKjBXU97JE0r1/WjrbfjKe9kJOYgCV8MsDN2HKdPDRrt68t3BqOQyFhnk028a8XsrM3C",
	"JJq1XaREW30z6NLvbpLfSLXD5mF8S8z74e2QbUz5ha79S5jko5cUBWAgKiCSrllr9P3q4ofm4eryArXR",
	"WAPsN4dXFz8cYwavLn6wEfimrtu4ca+6m41PkVCj6e6FIXiPFppNj6gJXhUzKpG5vtB7Wc/ZQ8oH67io",
	"cHL55t3Ly9cXr05RwnvCA9o1UZBRLgqsTYSEk5ToURcqT3FXExfRiFubwYrIQJvymgUbGFeakqz2k9t6",
	"FSMMm0PRc83OfBrlNIkAblmeo95q1KYDWlPhwCXPV1O+aUcmq3VBfcMsHVj/2avd7tsh0XZ15XuMznW7",
	"YNTuu25duHJNuSlsCDKTmgJs9G9VH2Ks4a27xYb6xqjs1itahZxP+Sd0iKn185Xnek1Yss7BvMX3xlat",
	"c/i1fgHgOmEwHod+5HpeGLnRZGyvl+LInYReEoVJPA6C0OstTdzY96JgEiRBOI7cpL8UJ+OJP4nj2Ivj",
	"MPG7Ja9+eG/3qbluUvsWVa7r+0HkJV4w8YIoCD037KFIkiSYBGMvqf/zG8D4v7spv0MHL7Yc3N6woYeK",
	"6+KHLbomXhQmSeRF/tiP3agvrUnkjf3EC/w49Dx3Em2IJPajSeDHfhBHQbwhyCSahJ6XoIB9z/X7S5No",
	"HEfxOHCjeBJ7kx3xXfzw2NL7m9iIva328T1qdz0/mbheEAZhmEwS35v0MLm+H0ZeHPtJjHIKNzh1x9HY",
	"Czwv9ryx68fRxodREPleMJmEQTL2k6QvPG88Hieh63pRGLquO/G/sPbtA+p3fS9y/dAbx0HshoHv9g3A",
	"nfiBG/m+F7jJJIq8Pi5/HI1jP5kkkR+EYeDHvbUgHIeu78eeO4n9SRL215IoHk/8MPYDPwmDcfSfCxwY",
	"6Nv0PBeyIBrDvKhmOV2fztUpeCBh39lbObQt19bnlaazasqmDEH4brDV2ypEgd2PqnKNSariZmdwZN44",
	"dM5S37ENUFwwhVkFhIQZyXLTbBU0A8bLSjd50zJfzUmV6y9PEFYo3YkjlUCbjbalqqIgcmVq3bYQbQUu",
	"cCtpu/y2YMFGb7NBR6WSBTZmVlnNcpZa7xF0ewZhCpcvexBhUMCM6ltKOTaqh44mptwcTnjNaQJ20SPA",
	"N/7mecXjnlZM+duuE++fU/zuU4q/QH/cFMC8Kqjsyl9vhCo5hdsl5VBKkVUp+tRa3Yeap0fvq/c3iN7B",
	"uvVz5LDdCPxZJOEfL4kjW+IjGsQHof9SfeDjdSsmK+8pHvcUjnuKxj0Fozfl77+l7L9Kym6z096E2F1y",
	"1ZEFRlDHFvywTfUPzO45JfIsJemS9rL6PWav6Uc9KnPCtkS07a074qBFqVfQQq9DocENhg6abdja0Zoq",
	"6JfVlKSFuKFA8hwo10b+cymK9qS9ZqUvacluiKaNqBd0oH4SJTVa5i8z69x6QfULKo4oBOw/qhB40VlX",
	"KjJqA13Ac3dixhmCQ0eA5o7yqAi/xoRQDKbv6cecruAQHvP02EdRvMrzu68tfLygen1PmgLjcwFkJioN",
	"hAORlDjwM4rHVAHmtocyvaQSGm1gsGwEBiezSpsbnZnQy9N9MWPZzf8NNgFthdyMo+zMytU3b2ZWEASH",
	"jJaUZ5Tr9q5YWZ+pGvuB4m7mF3fFfdVPdO2V2+WPLQtGeC3h8yHCMc/5k0ezi47QXUobjHBLpBkdq0rU",
	"Y0YXkmQ0gxOiIacEy0FOm4kgxqGZScGt7VBKw9zpV5cWWzO6ePPyyZYx9QwzE61VtlXxfT1qCxdZgXpp",
	"tjWU0CubTXxvDffMhCBlQwfxhgImQ9vYtNKySnUlKZwwrrGgL1mqbKhnbYDq1AwofPVN3j8VbdpmM/Si",
	"niIIYHNYiQpuSd1vLMkNhSf1hif9imR992RkZ+6/++tts98WAea++3l38b4npPfpGYrrMyFySvgjVO0P",
	"GV3qZp4GbPvyR+trTBHd1NWeoF4oQUafSqE0JoW++xy01zfNB4B2CVe/eBfgXVzsM84W/EMM9IhM/dn1",
	"6LOr/8VI/tPV5YWpY4wbG1q/vtITo9YWpUwraAqdQZ0aH9qNh199APr18vWV4VK9P1lqXarz0Yhy55Z9",
	"YCXNGHGEXIzw1+jy9dV1KjLGF9dqpTQtTrvmqT87ppdEY/SachO+TIw3gxvrq/Xhi/XnrleP6J7ijgdd",
	"rnef2O2T3z2NDRia56xUTPUgoYGxRSUqVQ9GbAHtEeI4TvPsuZv39+Zg897Le9z1tINW399vvutj2Fti",
	"4yePeJXfT76tsupU85jHXtDN1eybqmlvwY7Qd+8ju3d72nv+fK33YJu5mObXtuZTkT9kSkfk6mkPYk/3",
	"e/HsPygU+aPp/1ZALvjChpzo3mwnlIRJBZKWkirKdXtaKspSKKaRbcmRXTEHAjNRcYwDMBMfG+nNZuLj",
	"U3N/mNih5wTROLRdx3O9uP4ZxOZE/92SqXpkQtGcptr09zvRI2d192TKF6Y28DnwPWJtxG6GztcTHDZW",
	"24yjMc1YPVq6Hrqb8k2vBaKAwG1tZTU5iKM7y9l/covMHt1Ym4PburRS9d+bao7ttADSXo6kW0dJrRtt",
	"uZCQw/6CIj5mBKoZgFqPP/05B5TekoxVyqTpXNT1ApyYAVRkuM2OpwcNz5iJrAE1/bNxFPQTdI4Osg1T",
	"bjhvX2yZfePqBtJTDO0ODNH3GQb8WObb0nCcCX8T8lFCrmk7cvjtAhT9rTID82L+4EBNIM0FsliKfLVA",
	"tZg8/qR++wTqg25kbs6k0rWIiNoBC1NeVEqjxMx9LSnoaePlDeSnruMmQWC0kExijPC+V/+ceK59MP7b",
	"m986sJMLpvxB2aChpSPqsbSMBevxem6IuM+XBvO6qZfMicVxrvhIM5LOlP+ypLw3i8hUfaFhN8cG2AfR",
	"rM46zYVHh6IdfMSd9YbGo7sdvZHI7U1Tvkba7ne++MCj6V1TdfOVni4brht9Hmwz/QfcbfzciPBbA7rd",
	"gH7rP7/1n9/6z79h//mHtp9/h+7zW/P5xfuib73nNxn/BVvPP7bz/GMbz6+27/zTN1SvsFhsRm8UFESn",
	"S5SuokSmS6zIMlaPUe5pttQtWSzqf2FncLwB0+bnDtDsMLQedjd/PX8uZFHHKaYwcdMt3hrcLd3m5wbV",
	"FfuddBvlLnWR30Nwhw/+8e6nV4bwB9P6CdvJu147K9rB1u2W9o2k85wtlnq3px26/K5/3e8ag+3s8XPK",
	"m5KR65GFvhieXb69grLlA+pDnKt2onHQCO/u/i8AAP//M8Tl1wBPAAA=",
}

// GetOpenAPISpec returns the Swagger specification corresponding to the generated code
// in this file.
func GetOpenAPISpec() (*openapi3.T, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewLoader().LoadFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
