hosts:
  zebedee: http://localhost:8082
  files: http://localhost:26900
  download-publishing: http://localhost:23600
  download-web: http://localhost:23601
  identity: http://localhost:25600
  upload: http://localhost:25100
